### ISSUE TITLE
remove serial

### ISSUE THREAD

**Issue by collectionofcells** [Andrej-Antipov/Asrock-Z690-PG-Reptide-hackintosh#1]
just FYI the shared  opencore config.plist has your generated serial #, not sure if this is a security risk as other users usually remove them while sharing EFI files on forums.

**Comment by Andrej-Antipov** [comment]
This is automatically generated data by macserial utility, the EFI got user should understand that he needs to change not only the serial, but also other data, especially System ID, to get a unique identifier of his computer. In any case, when I publish new versions of EFI, I generate new identification data.
